export const categories = [
  {
    id: 1,
    name: "Процесори",
    route: "processors",
  },
  {
    id: 2,
    name: "РАМ Мемории",
    route: "ram-memory",
  },
  {
    id: 3,
    name: "Графички Картички",
    route: "graphics-cards",
  },
  {
    id: 3,
    name: "Графички Картички",
    route: "graphics-cards",
  },
  {
    id: 3,
    name: "Графички Картички",
    route: "graphics-cards",
  },
  {
    id: 3,
    name: "Графички Картички",
    route: "graphics-cards",
  },
  {
    id: 3,
    name: "Графички Картички",
    route: "graphics-cards",
  },
  {
    id: 3,
    name: "Графички Картички",
    route: "graphics-cards",
  },
  {
    id: 3,
    name: "Графички Картички",
    route: "graphics-cards",
  },
  {
    id: 3,
    name: "Графички Картички",
    route: "graphics-cards",
  },
  {
    id: 3,
    name: "Графички Картички",
    route: "graphics-cards",
  },
  {
    id: 3,
    name: "Графички Картички",
    route: "graphics-cards",
  },
  {
    id: 3,
    name: "Графички Картички",
    route: "graphics-cards",
  },
];

export const products = [
  {
    id: 1,
    name: "Intel i3",
    route: "intel-core-i3",
    category: "processors",
    description: "A Proccessor by intel",
    isFeatured: true,
    price: 1543,
    isAvailable: true,
  },
  {
    id: 2,
    name: "DDR4",
    route: "kingston-ddr4",
    category: "ram-memory",
    description: "A Ram by kingston",
    isFeatured: false,
    price: 553,
    isAvailable: true,
  },
  {
    id: 3,
    name: "AMD 7770",
    route: "amd-hd-7770",
    category: "graphics-cards",
    description: "A gpu by amd",
    isFeatured: true,
    price: 11543,
    isAvailable: false,
  },
  {
    id: 3,
    name: "AMD 7770",
    route: "amd-hd-7770",
    category: "graphics-cards",
    description: "A gpu by amd",
    isFeatured: true,
    price: 11543,
    isAvailable: true,
  },
  {
    id: 3,
    name: "AMD 7770",
    route: "amd-hd-7770",
    category: "graphics-cards",
    description: "A gpu by amd",
    isFeatured: true,
    price: 11543,
    isAvailable: false,
  },
  {
    id: 3,
    name: "AMD 7770",
    route: "amd-hd-7770",
    category: "graphics-cards",
    description: "A gpu by amd",
    isFeatured: true,
    price: 11543,
    isAvailable: true,
  },
  {
    id: 3,
    name: "AMD 7770",
    route: "amd-hd-7770",
    category: "graphics-cards",
    description: "A gpu by amd",
    isFeatured: true,
    price: 11543,
    isAvailable: true,
  },
  {
    id: 3,
    name: "AMD 7770",
    route: "amd-hd-7770",
    category: "graphics-cards",
    description: "A gpu by amd",
    isFeatured: true,
    price: 11543,
    isAvailable: true,
  },
  {
    id: 3,
    name: "AMD 7770",
    route: "amd-hd-7770",
    category: "graphics-cards",
    description: "A gpu by amd",
    isFeatured: true,
    price: 11543,
    isAvailable: false,
  },
  {
    id: 3,
    name: "AMD 7770",
    route: "amd-hd-7770",
    category: "graphics-cards",
    description: "A gpu by amd",
    isFeatured: true,
    price: 11543,
    isAvailable: false,
  },
  {
    id: 3,
    name: "AMD 7770",
    route: "amd-hd-7770",
    category: "graphics-cards",
    description: "A gpu by amd",
    isFeatured: true,
    price: 11543,
    isAvailable: true,
  },
  {
    id: 3,
    name: "AMD 7770",
    route: "amd-hd-7770",
    category: "graphics-cards",
    description: "A gpu by amd",
    isFeatured: true,
    price: 11543,
    isAvailable: false,
  },
  {
    id: 3,
    name: "AMD 7770",
    route: "amd-hd-7770",
    category: "graphics-cards",
    description: "A gpu by amd",
    isFeatured: true,
    price: 11543,
    isAvailable: true,
  },
  {
    id: 3,
    name: "AMD 7770",
    route: "amd-hd-7770",
    category: "graphics-cards",
    description: "A gpu by amd",
    isFeatured: true,
    price: 11543,
    isAvailable: true,
  },
  {
    id: 3,
    name: "AMD 7770",
    route: "amd-hd-7770",
    category: "graphics-cards",
    description: "A gpu by amd",
    isFeatured: true,
    price: 11543,
    isAvailable: false,
  },
  {
    id: 3,
    name: "AMD 7770",
    route: "amd-hd-7770",
    category: "graphics-cards",
    description: "A gpu by amd",
    isFeatured: true,
    price: 11543,
    isAvailable: true,
  },
];
